### ISSUE TITLE
automatically create output directory if it doesn't exist

### ISSUE THREAD

**Issue by jeff-regier** [prob-ml/bliss#335]
```
regier@deeplearning-01:~/bliss$ poetry run bliss +experiment=sdss_sleep
Error executing job with overrides: ['+experiment=sdss_sleep']
Traceback (most recent call last):
  File "/home/regier/bliss/bliss/main.py", line 16, in main
    task(cfg)
  File "/home/regier/bliss/bliss/train.py", line 60, in train
    assert Path(p).exists(), f"path {Path(p).as_posix()} does not exist"
AssertionError: path /home/regier/bliss/output does not exist

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by dereklhansen** [comment]
Still relevant; I've run into this issue too.
